var mydiv =document.createElement('div');
    mydiv.setAttribute('class', 'show');
    towdiv =document.createElement('div');
    towdiv.setAttribute('class', 'tow');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.13 PM.jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.color='white';
    but.style.textAlign='center';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('tavuk فروج ');
    but.appendChild(text);
    towdiv.appendChild(img);
    towdiv.appendChild(but); 
    mydiv.appendChild(towdiv);
    but.style.margin='0';

    threediv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.13 PM (1).jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('مشاوي الدجاج');
    but.appendChild(text);
    threediv.appendChild(img);
    threediv.appendChild(but);
    mydiv.appendChild(threediv);
    but.style.margin='0';

    fourdiv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.12 PM.jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('وجبات الرز');
    but.appendChild(text);
    fourdiv.appendChild(img);
    fourdiv.appendChild(but);
    mydiv.appendChild(fourdiv);
    but.style.margin='0';

    fivediv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.12 PM (2).jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('مندي القصور');
    but.appendChild(text);
    fivediv.appendChild(img);
    fivediv.appendChild(but);
    mydiv.appendChild(fivediv);
    but.style.margin='0';

    sixdiv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.12 PM (1).jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('وجبات الرز');
    but.appendChild(text);
    sixdiv.appendChild(img);
    sixdiv.appendChild(but);
    mydiv.appendChild(sixdiv);
    but.style.margin='0';

    sevendiv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.11 PM.jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('الكبب');
    but.appendChild(text);
    sevendiv.appendChild(img);
    sevendiv.appendChild(but);
    mydiv.appendChild(sevendiv);
    but.style.margin='0';

    eightdiv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.11 PM (1).jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('شاورما');
    but.appendChild(text);
    eightdiv.appendChild(img);
    eightdiv.appendChild(but);
    mydiv.appendChild(eightdiv);
    but.style.margin='0';

    ninediv=document.createElement('div');
    img=document.createElement('img');
    img.setAttribute('src', 'WhatsApp Image 2023-02-04 at 12.37.10 PM.jpeg');
    img.setAttribute('width', '150px');
    img.setAttribute('height', '150px');
    img.style.borderRadius= '10px 10px 0 0';
    but=document.createElement('h4');
    but.style.width='10';
    but.style.hieght='10';
    but.style.backgroundColor='#FFD700'; 
    but.style.textAlign='center';
    but.style.color='white';
    but.style.padding='10px';
    but.style.borderRadius= '0 0 10px 10px';
    text=document.createTextNode('مشاوي لحم');
    but.appendChild(text);
    ninediv.appendChild(img);
    ninediv.appendChild(but);
    mydiv.appendChild(ninediv);

    
    
    document.body.appendChild(mydiv);
    mydiv.style.display='flex';
    mydiv.style.backgroundColor='black'
    mydiv.style.padding='10px'
    mydiv.style.flexWrap= 'wrap';
    mydiv.style.justifyContent='space-between';
    but.style.margin='0';
    
    
    
    